[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "GameReact Core"
authors = [{name = "Benjamin Wagner", email = "51082373+btinet@users.noreply.github.com"}]
dynamic = ["version", "description"]
